<?php
router::addFunction("list","login");
router::addFunction("recoverView","login");
router::addFunction('show_View','login');
router::addFunction('register','login');
router::addFunction('login','login');
router::addFunction('menu','login');
router::addFunction('verify','login');
router::addFunction('verify_user','login');
router::addFunction('recover','login');
router::addFunction('recover_password','login');
router::addFunction('socialGit','login');
router::addFunction('socialGoogle','login');